# Generated by Django 5.2.4 on 2025-08-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='information',
        ),
    ]
