# Generated by Django 5.2.4 on 2025-08-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_date_joined_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_crete',
            field=models.CharField(blank=True),
        ),
    ]
