# Generated by Django 5.2.4 on 2025-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_date_crete'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isDecided',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='voice',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
