# Generated by Django 5.2.4 on 2025-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_comment_owner_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_crete']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_crete',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
