# Generated by Django 5.2.4 on 2025-08-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userprofile_options_alter_comment_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
