# Generated by Django 5.2.3 on 2025-08-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_crete',
            new_name='created_at',
        ),
    ]
